// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using ToucanTesting.Data;
using ToucanTesting.Models;

namespace ToucanTesting.Migrations
{
    [DbContext(typeof(ToucanDbContext))]
    [Migration("20180518124848_AddHasCriteriaToTestCase")]
    partial class AddHasCriteriaToTestCase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ToucanTesting.Models.ExpectedResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<long>("TestCaseId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseId");

                    b.ToTable("ExpectedResults");
                });

            modelBuilder.Entity("ToucanTesting.Models.TestAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("Sequence");

                    b.Property<long>("TestCaseId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseId");

                    b.ToTable("TestActions");
                });

            modelBuilder.Entity("ToucanTesting.Models.TestCase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AutomationId")
                        .HasMaxLength(4);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime?>("DisabledAt");

                    b.Property<bool>("HasCriteria");

                    b.Property<bool>("IsAutomated");

                    b.Property<bool>("IsEnabled");

                    b.Property<DateTime?>("LastTested");

                    b.Property<int>("Priority");

                    b.Property<long>("TestModuleId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("TestModuleId");

                    b.ToTable("TestCases");
                });

            modelBuilder.Entity("ToucanTesting.Models.TestCondition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<long>("TestCaseId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseId");

                    b.ToTable("TestConditions");
                });

            modelBuilder.Entity("ToucanTesting.Models.TestIssue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(16);

                    b.Property<string>("TestCaseDescription");

                    b.Property<long>("TestCaseId");

                    b.Property<string>("TestModuleName");

                    b.Property<string>("TestRunName");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseId");

                    b.ToTable("TestIssues");
                });

            modelBuilder.Entity("ToucanTesting.Models.TestModule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("DisabledAt");

                    b.Property<bool>("IsEnabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<long>("TestSuiteId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("TestSuiteId");

                    b.ToTable("TestModules");
                });

            modelBuilder.Entity("ToucanTesting.Models.TestResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("Status");

                    b.Property<long>("TestCaseId");

                    b.Property<long>("TestModuleId");

                    b.Property<long>("TestRunId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("TestRunId");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("ToucanTesting.Models.TestRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<long>("TestSuiteId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("TestSuiteId");

                    b.ToTable("TestRuns");
                });

            modelBuilder.Entity("ToucanTesting.Models.TestSuite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsEnabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("TestSuites");
                });

            modelBuilder.Entity("ToucanTesting.Models.ExpectedResult", b =>
                {
                    b.HasOne("ToucanTesting.Models.TestCase")
                        .WithMany("ExpectedResults")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ToucanTesting.Models.TestAction", b =>
                {
                    b.HasOne("ToucanTesting.Models.TestCase")
                        .WithMany("TestActions")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ToucanTesting.Models.TestCase", b =>
                {
                    b.HasOne("ToucanTesting.Models.TestModule", "TestModule")
                        .WithMany("TestCases")
                        .HasForeignKey("TestModuleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ToucanTesting.Models.TestCondition", b =>
                {
                    b.HasOne("ToucanTesting.Models.TestCase")
                        .WithMany("TestConditions")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ToucanTesting.Models.TestIssue", b =>
                {
                    b.HasOne("ToucanTesting.Models.TestCase")
                        .WithMany("TestIssues")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ToucanTesting.Models.TestModule", b =>
                {
                    b.HasOne("ToucanTesting.Models.TestSuite")
                        .WithMany("TestModules")
                        .HasForeignKey("TestSuiteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ToucanTesting.Models.TestResult", b =>
                {
                    b.HasOne("ToucanTesting.Models.TestRun")
                        .WithMany("TestResults")
                        .HasForeignKey("TestRunId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ToucanTesting.Models.TestRun", b =>
                {
                    b.HasOne("ToucanTesting.Models.TestSuite", "TestSuite")
                        .WithMany()
                        .HasForeignKey("TestSuiteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
